// Auto-generated by cbindgen. Do not edit.

#ifndef RUFFLE_FFI_H
#define RUFFLE_FFI_H

#pragma once

// This file is auto-generated by cbindgen. Do not edit manually.

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * The resolved access decision supplied by Swift when constructing a player.
 */
typedef enum RuffleAccessPolicy {
  RuffleAccessPolicy_Deny = 0,
  RuffleAccessPolicy_Allow = 1,
} RuffleAccessPolicy;

/**
 * Result codes for FFI operations.
 */
typedef enum RuffleResult {
  RuffleResult_Ok = 0,
  RuffleResult_ErrorNullPointer = -1,
  RuffleResult_ErrorLockPoisoned = -2,
  RuffleResult_ErrorInvalidArgument = -3,
  RuffleResult_ErrorRendererInit = -4,
  RuffleResult_ErrorLoadFailed = -5,
} RuffleResult;

/**
 * Root movie loading state exposed to Swift.
 */
typedef enum RuffleLoadState {
  RuffleLoadState_Idle = 0,
  RuffleLoadState_Loading = 1,
  RuffleLoadState_Ready = 2,
  RuffleLoadState_Failed = 3,
} RuffleLoadState;

/**
 * A policy event emitted by the Navigator after redacting the request target.
 */
typedef enum RuffleDiagnosticKind {
  RuffleDiagnosticKind_FilesystemDenied = 0,
  RuffleDiagnosticKind_NetworkDenied = 1,
  RuffleDiagnosticKind_NetworkUnsupported = 2,
  RuffleDiagnosticKind_UnsupportedScheme = 3,
  RuffleDiagnosticKind_NavigationDenied = 4,
  RuffleDiagnosticKind_SocketDenied = 5,
} RuffleDiagnosticKind;

/**
 * Stage scale mode.
 */
typedef enum RuffleScaleMode {
  RuffleScaleMode_ShowAll = 0,
  RuffleScaleMode_NoScale = 1,
  RuffleScaleMode_ExactFit = 2,
  RuffleScaleMode_NoBorder = 3,
} RuffleScaleMode;

/**
 * Letterbox mode.
 */
typedef enum RuffleLetterbox {
  RuffleLetterbox_Off = 0,
  RuffleLetterbox_Fullscreen = 1,
  RuffleLetterbox_On = 2,
} RuffleLetterbox;

/**
 * Opaque handle to a Ruffle player instance.
 * The Swift side holds this as `OpaquePointer`.
 */
typedef struct RufflePlayer RufflePlayer;

/**
 * Opaque handle to a wgpu renderer bound to a Metal layer.
 */
typedef struct RuffleRenderer RuffleRenderer;

/**
 * Player configuration provided by Swift at creation time.
 */
typedef struct RuffleConfig {
  /**
   * Stage width in pixels.
   */
  unsigned int width;
  /**
   * Stage height in pixels.
   */
  unsigned int height;
  /**
   * Retina scale factor (e.g. 2.0 for Retina).
   */
  float scale_factor;
  /**
   * Stage quality.
   */
  int quality;
  /**
   * Whether to autoplay on load.
   */
  bool autoplay;
  /**
   * Max ActionScript execution duration in seconds. 0 = unlimited.
   */
  float max_execution_secs;
  /**
   * Resolved policy for HTTP(S), navigation, and socket access.
   */
  enum RuffleAccessPolicy network_access;
  /**
   * Resolved policy for local SWF subresources.
   */
  enum RuffleAccessPolicy filesystem_access;
} RuffleConfig;

/**
 * C-compatible string wrapper. Caller must free with `ruffle_string_free`.
 */
typedef struct RuffleString {
  char *data;
  unsigned int len;
} RuffleString;

/**
 * Owned list of strings returned across FFI. Caller must free with `ruffle_string_list_free`.
 */
typedef struct RuffleStringList {
  struct RuffleString *data;
  unsigned int len;
} RuffleStringList;

/**
 * Owned bytes returned across FFI. Caller must free with `ruffle_bytes_free`.
 */
typedef struct RuffleBytes {
  uint8_t *data;
  unsigned int len;
} RuffleBytes;

/**
 * Root movie loading snapshot for UI polling.
 */
typedef struct RuffleLoadInfo {
  enum RuffleLoadState state;
  enum RuffleResult error;
} RuffleLoadInfo;

typedef struct RuffleDiagnostic {
  enum RuffleDiagnosticKind kind;
  struct RuffleString target;
} RuffleDiagnostic;

/**
 * A key event forwarded from Swift.
 */
typedef struct RuffleKeyEvent {
  /**
   * Physical key code (USB HID usage).
   */
  unsigned int key_code;
  /**
   * Character code point (0 if not a character key).
   */
  unsigned int char_code;
  /**
   * True if key is pressed down, false if released.
   */
  bool is_down;
  /**
   * Modifier keys bitmask: bit0=shift, bit1=control, bit2=alt, bit3=command.
   */
  unsigned int modifiers;
} RuffleKeyEvent;

/**
 * A mouse event forwarded from Swift.
 */
typedef struct RuffleMouseEvent {
  /**
   * X position in stage coordinates.
   */
  float x;
  /**
   * Y position in stage coordinates.
   */
  float y;
  /**
   * Event type: 0=move, 1=left-down, 2=left-up, 3=right-down, 4=right-up, 5=scroll.
   */
  int event_type;
  /**
   * Scroll delta Y (only for scroll events).
   */
  float scroll_delta;
} RuffleMouseEvent;

/**
 * Playback state snapshot for UI polling.
 */
typedef struct RufflePlaybackInfo {
  uint32_t current_frame;
  uint32_t total_frames;
  float frame_rate;
  float elapsed_time_secs;
  bool is_playing;
  bool is_looping;
  float speed_multiplier;
} RufflePlaybackInfo;

/**
 * SWF metadata returned from the player.
 */
typedef struct RuffleMetadata {
  uint8_t swf_version;
  uint8_t player_version;
  bool is_action_script_3;
  float frame_rate;
  uint32_t movie_width;
  uint32_t movie_height;
  uint32_t total_frames;
  bool uses_avm2;
  uint32_t background_color;
} RuffleMetadata;

/**
 * Create a new Ruffle player with the given configuration.
 * Returns an opaque handle, or null on failure.
 *
 * # Safety
 * The returned handle must be freed with `ruffle_player_free`.
 */
struct RufflePlayer *ruffle_player_create(struct RuffleConfig config);

/**
 * Create a new Ruffle player using a renderer created by `ruffle_renderer_create`.
 * Returns an opaque handle, or null on failure.
 *
 * # Safety
 * The returned handle must be freed with `ruffle_player_free`.
 */
struct RufflePlayer *ruffle_player_create_with_renderer(struct RuffleConfig config,
                                                        struct RuffleRenderer *renderer);

/**
 * Create a player with SharedObject storage isolated to a stable library ID.
 * Returns null when the root directory or namespace is invalid.
 *
 * # Safety
 * `storage_root` and `library_id` must be non-null, NUL-terminated UTF-8 strings.
 */
struct RufflePlayer *ruffle_player_create_with_renderer_and_storage(struct RuffleConfig config,
                                                                    struct RuffleRenderer *renderer,
                                                                    const char *storage_root,
                                                                    const char *library_id);

enum RuffleResult ruffle_storage_list(const char *storage_root,
                                      const char *library_id,
                                      struct RuffleStringList *out);

enum RuffleResult ruffle_storage_read(const char *storage_root,
                                      const char *library_id,
                                      const char *name,
                                      struct RuffleBytes *out);

enum RuffleResult ruffle_storage_replace(const char *storage_root,
                                         const char *library_id,
                                         const char *name,
                                         const uint8_t *data,
                                         unsigned int len);

enum RuffleResult ruffle_storage_delete(const char *storage_root,
                                        const char *library_id,
                                        const char *name);

enum RuffleResult ruffle_storage_get_size(const char *storage_root,
                                          const char *library_id,
                                          const char *name,
                                          uint64_t *out);

enum RuffleResult ruffle_storage_get_usage(const char *storage_root,
                                           const char *library_id,
                                           uint64_t *used,
                                           uint64_t *quota);

/**
 * Free a player handle.
 *
 * # Safety
 * `ptr` must be a valid pointer returned by `ruffle_player_create`, and must not be used after this call.
 */
void ruffle_player_free(struct RufflePlayer *ptr);

/**
 * Load a SWF from a file URL (file:// or http(s)://).
 *
 * # Safety
 * `ptr` must be valid. `url` must be a null-terminated UTF-8 C string.
 * `url` must remain valid for the duration of this call.
 */
enum RuffleResult ruffle_player_load_url(struct RufflePlayer *ptr, const char *url);

/**
 * Load a SWF from a byte buffer.
 *
 * # Safety
 * `ptr` must be valid. `data` must point to `len` valid bytes.
 */
enum RuffleResult ruffle_player_load_data(struct RufflePlayer *ptr,
                                          const uint8_t *data,
                                          unsigned int len);

/**
 * Load a SWF from a byte buffer using the provided URL as its base URL.
 *
 * # Safety
 * `ptr` must be valid. `data` must point to `len` valid bytes.
 * `url` must be a null-terminated UTF-8 C string.
 */
enum RuffleResult ruffle_player_load_data_with_url(struct RufflePlayer *ptr,
                                                   const uint8_t *data,
                                                   unsigned int len,
                                                   const char *url);

/**
 * Get the current root movie loading state.
 *
 * # Safety
 * `ptr` and `info` must be valid pointers.
 */
enum RuffleResult ruffle_player_get_load_info(const struct RufflePlayer *ptr,
                                              struct RuffleLoadInfo *info);

/**
 * Pop the next redacted Navigator policy event. Returns false when no event is pending.
 *
 * # Safety
 * `ptr` and `diagnostic` must be valid pointers. The returned target must be freed with
 * `ruffle_string_free`.
 */
bool ruffle_player_next_diagnostic(struct RufflePlayer *ptr, struct RuffleDiagnostic *diagnostic);

/**
 * Advance the player by `dt` seconds.
 *
 * # Safety
 * `ptr` must be valid.
 */
enum RuffleResult ruffle_player_tick(struct RufflePlayer *ptr, float dt);

/**
 * Render the current frame.
 *
 * # Safety
 * `ptr` must be valid.
 */
enum RuffleResult ruffle_player_render(struct RufflePlayer *ptr);

/**
 * Set whether the player is playing or paused.
 *
 * # Safety
 * `ptr` must be valid.
 */
enum RuffleResult ruffle_player_set_playing(struct RufflePlayer *ptr, bool playing);

/**
 * Check if the player is currently playing.
 *
 * # Safety
 * `ptr` must be valid.
 */
bool ruffle_player_is_playing(const struct RufflePlayer *ptr);

/**
 * Set volume (0.0 to 1.0).
 *
 * # Safety
 * `ptr` must be valid.
 */
enum RuffleResult ruffle_player_set_volume(struct RufflePlayer *ptr, float volume);

/**
 * Get current volume.
 *
 * # Safety
 * `ptr` must be valid.
 */
float ruffle_player_get_volume(const struct RufflePlayer *ptr);

/**
 * Forward a key event from Swift.
 *
 * # Safety
 * `ptr` must be valid.
 */
enum RuffleResult ruffle_player_key_event(struct RufflePlayer *ptr, struct RuffleKeyEvent event);

/**
 * Forward a mouse event from Swift.
 *
 * # Safety
 * `ptr` must be valid.
 */
enum RuffleResult ruffle_player_mouse_event(struct RufflePlayer *ptr,
                                            struct RuffleMouseEvent event);

/**
 * Update the viewport dimensions (e.g. on window resize).
 *
 * # Safety
 * `ptr` must be valid.
 */
enum RuffleResult ruffle_player_set_viewport(struct RufflePlayer *ptr,
                                             unsigned int width,
                                             unsigned int height,
                                             float scale_factor);

/**
 * Set fullscreen state.
 *
 * # Safety
 * `ptr` must be valid.
 */
enum RuffleResult ruffle_player_set_fullscreen(struct RufflePlayer *ptr, bool fullscreen);

/**
 * Get a snapshot of the current playback state.
 *
 * # Safety
 * `ptr` must be valid. `info` must be a valid pointer to a `RufflePlaybackInfo`.
 */
enum RuffleResult ruffle_player_get_playback_info(const struct RufflePlayer *ptr,
                                                  struct RufflePlaybackInfo *info);

/**
 * Get SWF metadata.
 *
 * # Safety
 * `ptr` must be valid. `out` must be a valid pointer to a `RuffleMetadata`.
 */
enum RuffleResult ruffle_player_get_metadata(struct RufflePlayer *ptr, struct RuffleMetadata *out);

/**
 * Set the stage background color used by Ruffle when the SWF does not provide one.
 * Color format is AARRGGBB.
 *
 * # Safety
 * `ptr` must be valid.
 */
enum RuffleResult ruffle_player_set_background_color(struct RufflePlayer *ptr, unsigned int color);

/**
 * Seek to a specific frame number.
 *
 * # Safety
 * `ptr` must be valid.
 */
enum RuffleResult ruffle_player_seek_frame(struct RufflePlayer *ptr, uint32_t frame);

/**
 * Seek to a time in seconds.
 *
 * # Safety
 * `ptr` must be valid.
 */
enum RuffleResult ruffle_player_seek_time(struct RufflePlayer *ptr, float seconds);

/**
 * Step backward by N frames.
 *
 * # Safety
 * `ptr` must be valid.
 */
enum RuffleResult ruffle_player_step_back(struct RufflePlayer *ptr, uint32_t frames);

/**
 * Rewind to the first frame.
 *
 * # Safety
 * `ptr` must be valid.
 */
enum RuffleResult ruffle_player_rewind(struct RufflePlayer *ptr);

/**
 * Set whether playback should loop. (Stub — looping is handled on Swift side.)
 *
 * # Safety
 * `ptr` must be valid.
 */
enum RuffleResult ruffle_player_set_looping(struct RufflePlayer *_ptr, bool _looping);

/**
 * Set playback speed multiplier. (Stub — speed is applied via dt on Swift side.)
 *
 * # Safety
 * `ptr` must be valid.
 */
enum RuffleResult ruffle_player_set_speed(struct RufflePlayer *_ptr, float _speed);

/**
 * Set the stage scale mode.
 *
 * # Safety
 * `ptr` must be valid.
 */
enum RuffleResult ruffle_player_set_scale_mode(struct RufflePlayer *ptr, enum RuffleScaleMode mode);

/**
 * Set the letterbox mode.
 *
 * # Safety
 * `ptr` must be valid.
 */
enum RuffleResult ruffle_player_set_letterbox_mode(struct RufflePlayer *ptr,
                                                   enum RuffleLetterbox mode);

/**
 * Set the stage quality.
 *
 * # Safety
 * `ptr` must be valid.
 */
enum RuffleResult ruffle_player_set_quality(struct RufflePlayer *ptr, int quality);

/**
 * Recreate the renderer's GPU surface with a new CAMetalLayer.
 *
 * This is called when the NSView/MTKView is recreated (e.g. after navigating
 * away and back in the SwiftUI sidebar). Unlike `ruffle_renderer_recreate_surface`,
 * this operates on the Player which still owns the render backend.
 *
 * # Safety
 * `ptr` must be valid. `metal_layer` must be a valid pointer to a `CAMetalLayer`.
 */
enum RuffleResult ruffle_player_recreate_surface(struct RufflePlayer *ptr,
                                                 void *metal_layer,
                                                 unsigned int width,
                                                 unsigned int height);

/**
 * Get the SWF stage width.
 *
 * # Safety
 * `ptr` must be valid.
 */
unsigned int ruffle_player_stage_width(const struct RufflePlayer *ptr);

/**
 * Get the SWF stage height.
 *
 * # Safety
 * `ptr` must be valid.
 */
unsigned int ruffle_player_stage_height(const struct RufflePlayer *ptr);

/**
 * Free a string returned by the FFI.
 *
 * # Safety
 * `s` must have been returned by an FFI function.
 */
void ruffle_string_free(struct RuffleString s);

void ruffle_bytes_free(struct RuffleBytes bytes);

void ruffle_string_list_free(struct RuffleStringList list);

/**
 * Create a wgpu renderer from a CAMetalLayer pointer.
 *
 * The `metal_layer` must be a valid `CAMetalLayer*` from a `MTKView` or `NSView`.
 * The layer must remain alive for the lifetime of the returned renderer.
 *
 * # Safety
 * `metal_layer` must be a valid pointer to a `CAMetalLayer`.
 */
struct RuffleRenderer *ruffle_renderer_create(void *metal_layer,
                                              unsigned int width,
                                              unsigned int height,
                                              float _scale_factor);

/**
 * Resize the renderer surface (e.g. on window resize).
 *
 * # Safety
 * `ptr` must be a valid renderer handle.
 */
enum RuffleResult ruffle_renderer_resize(struct RuffleRenderer *ptr,
                                         unsigned int width,
                                         unsigned int height,
                                         float scale_factor);

/**
 * Recreate the renderer's surface with a new CAMetalLayer.
 *
 * This allows updating the Metal layer when the NSView/MTKView is
 * recreated (e.g. after navigating away and back), without destroying
 * the player or losing playback state.
 *
 * # Safety
 * `ptr` must be a valid renderer handle. `metal_layer` must be a valid
 * pointer to a `CAMetalLayer`.
 */
enum RuffleResult ruffle_renderer_recreate_surface(struct RuffleRenderer *ptr,
                                                   void *metal_layer,
                                                   unsigned int width,
                                                   unsigned int height);

/**
 * Get the surface texture format (for Metal interop if needed).
 *
 * # Safety
 * `ptr` must be a valid renderer handle.
 */
unsigned int ruffle_renderer_surface_format(const struct RuffleRenderer *ptr);

/**
 * Present the current frame.
 *
 * # Safety
 * `ptr` must be a valid renderer handle.
 */
enum RuffleResult ruffle_renderer_present(struct RuffleRenderer *ptr);

/**
 * Free a renderer handle.
 *
 * # Safety
 * `ptr` must be a valid pointer returned by `ruffle_renderer_create`.
 */
void ruffle_renderer_free(struct RuffleRenderer *ptr);

/**
 * Create a wgpu RenderBackend from the renderer's descriptors.
 * This is used internally to wire up the renderer to the Player.
 *
 * # Safety
 * `ptr` must be a valid renderer handle.
 */
void *ruffle_renderer_create_backend(const struct RuffleRenderer *ptr);

#endif  /* RUFFLE_FFI_H */
